FROM oven/bun:alpine AS builder

ENV VITE_API_URL=http://localhost:3000/v1

WORKDIR /tmp

COPY bun.lock package.json ./
RUN bun install

COPY ./src ./src
COPY vite.config.js ./
RUN bun run build

FROM nginx:alpine-slim

COPY --from=builder /tmp/dist /usr/share/nginx/html

EXPOSE 80

